name: Send data using pipe

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build receiver for pipe
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o receivestream *.c*

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build sender for pipe
      run: mvn install

    - name: pipe
      run:  java -jar BatteryMgmtSender-0.0.1-SNAPSHOT.jar | ./receivestream
